# Dockerfile — auto-generated by CI fixer
# The CI pipeline reported a Docker build failure.
# Errors from the failing run:
#   2026-05-15T22:09:26.0451167Z ##[error]Process completed with exit code 2.
#   2026-05-15T22:09:26.0451086Z ##[error]Process completed with exit code 2.
#
# Replace the template below with your actual build steps.
FROM ubuntu:22.04
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*
CMD ["bash"]
